<a href="https://colab.research.google.com/github/blaxman37/Laxman_github/blob/main/Copy_of_Chipotle_02_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep = '\t')

In [ ]:
chipo.head(50)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
10,5,1,Chips and Guacamole,NaN,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
14,7,1,Chips and Guacamole,NaN,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
18,9,2,Canned Soda,[Sprite],2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
20,10,1,Chips and Guacamole,NaN,4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
24,12,1,Izze,[Grapefruit],3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
30,15,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",8.99
32,16,1,Side of Chips,NaN,1.69
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99
34,17,1,Bottled Water,NaN,1.09
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
37,18,1,Chips and Guacamole,NaN,4.45
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
40,19,1,Chips,NaN,2.15
41,20,1,Chips and Guacamole,NaN,4.45
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.75
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
45,21,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",10.98
46,21,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",8.99
47,21,1,Izze,[Blackberry],3.39
48,22,1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99
49,22,1,Chips and Guacamole,NaN,3.99

### Step 4. How many products cost more than $10.00?

In [ ]:
new_type = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(new_type)

In [ ]:
chipo.item_price.dtype

dtype('float64')

In [ ]:
chipo[chipo['item_price']>10]['item_name'].nunique()

31

### Step 6. Sort by the name of the item

In [ ]:
#hint: use sort_values()

chipo.sort_values(['item_name'],ascending = True)

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [ ]:
chipo.groupby(['item_name']).max().sort_values('item_price',ascending = False).head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chips and Fresh Tomato Salsa,1790,15,NaN,44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:


chipo[chipo['item_name'] == 'Veggie Salad Bowl'].sum().loc['quantity']

18

### Step 9. How many times did someone order more than one Canned Soda?

In [ ]:
chipo_times = chipo[(chipo['quantity'] > 1) & (chipo['item_name'] == 'Canned Soda')]
chipo_times.quantity

18      2
51      2
162     2
171     2
350     2
352     2
698     2
700     2
909     2
1091    2
1092    2
1944    2
2135    2
2235    4
2905    2
2906    2
3152    2
3364    2
3592    2
3866    2
Name: quantity, dtype: int64